### PR TITLE
Fixes #35: Add watchdog entry at start of creating a snapshot

### LINKED ISSUE #35: Add watchdog entry at start of creating a snapshot
The demo module already creates a watchdog entry after a snapshot is restored. It would be helpful if it also creates a watchdog entry at the start of creating a snapshot so that it is part of the log that is included in the snapshot and will be visible when the snapshot is restored. This will help confirm the timing of events if one is looking back through the log later to confirm when things happened.

I appreciate this is a feature request and I have made a fork of the repo and will try to submit a PR in the next day or so to address this issue.

### PR DESCRIPTION
**Pull request by robertgarrigos**
fixes #35

### CODE REVIEW

**Comment by izmeez** [comment]
@robertgarrigos Adding an extra line at 214 doesn't appear to be necessary.

Adding an extra comment to the start of the next hunk may add consistency:
`// Create watchdog notice for reference.`

Otherwise this looks good.

**Comment by izmeez** [comment]
Also, I wonder if the line that is added to watchdog should be changed, removing the for and adding a comma?
`'Created snapshot, %filename'`

**Comment by robertgarrigos** [comment]
@izmeez how about a colon (:)? ;-)

**Comment by izmeez** [comment]
A colon will be fine.

**Pull request merged**
